env:
  matrix:
  - DEVICE_NAME: raspberry-pi
  - DEVICE_NAME: raspberry-pi2
  - DEVICE_NAME: raspberrypi3

script:
- make build

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin;
    make publish;
    docker logout;
  fi
