env:
  global:
  - secure: TpKW0yI4mnEzycyRGRFOrMNIpJXJcJB8PIe3/+AQZ8vmdkKMDy+SrawirbpV1QSH8sMMVS/jsVOdKb7TIk0mJfWaTg7AyexFFJjF/ciws8ykbwRGREKpxastBfS0z0wdfQ37T50pv1H07AymhxKAwvUeFDPPGmeE2uK8xiPkXhshqwLj4LA1AOMkw+7iiOPxudfMt1IpzDe/+k9LzolqHUQMetRo3qn9F6cHxglzTXXW49jDt9JU74bmv5aJo9FQQWAnGcQcGYlj3T98+V3jGX1IBZ5KQ88dieub+Gl+4WTpBgtvvEBC0Pema1AO3+IWQ6q271i0qeofc+BChPjSHkb36g/hkKwem/mFU5pX1VJRFfwUtycoTIAYqDibm7SrailWRMBDoejBJ3bjsVSukwAEo9CNsjCxU1x26O/+k9fdcq6JpLJpx052qAD6FmalirlLypReYcLIqpRmOyG6Nw0vF+5wgDOYSTbOk+1juFLtwN1XgBsPHUkfYGLHRJaTEJ4gAjV+cVsNVFVQR5hBFL0CDvA7el1SQayAHSAyCO+HlP3ecvZhDvgaD5/NdjHw6yB8Nynlqfxuf/kwjk3VwMOP85R6fvJpjvmWbL1W0JNHwuaJ+ByLXYj6X9iLlzFzInD+qO52vLZpsSnge1wLYBLhst/70mADp3KmwowMlmY=
  - secure: WpWtCVW7Ui0k/4vAj8JfxYzy+XR9proC/ua4qs39T99ZF2Ph1uu0tvejFkqZY1DL1W89HPPj3hZchfNhbbu2ZxmlgjLWgu8VX7vAF06S4UpuAaM193WybADqRCEmqmeM6TlEce6aBk244d26SHiRzI+C/NvEqIgUB6CzsX9h5/Ja91umIItSt5CNReSXcZhk1uCqQEg9oHz/ZdfG9julbWWlqMEB3S9QD3RlB1tooxuqGCrbUTt8u44HgVPg5uv8Olg07Q/Y5tBqqy0OUvAVGI5ILA1PwR52CUSPZ4AmWILN5Twu6UGzvKf6TMtSXu++8aeBcN6XfQoiaWIRShliKqHoGFw21jINfQMYuLzgDHlV0PBnSNUvT4LLmrRz/iE+3PreX65K7lpQiLmZ38N9zgvMIGWGFAc4z02oEP1YV8iOdAP3KKmmbY/DWsyiNavDMfDgkr0HfJG38MBs6GTiVSdpgZ24o20eRZdaxGmhoRZ16S/HwIKJtvKpENnO9PUpqLmVM18ayTPcOGT5Z/iCwArxtPpi6Pbb/Ii8ISh8xqLgI1GtVYcfZnA92g19jDuCvg78kKVB6TPhCxRynboUVUbREvIBUJnEL0/p7TIpDqy4V5+qHrCSRznXSTlgZtx4cZwsBCYh6B72Y31T1JZVdnkWwA/6HKBsuuLsNMJarL8=
  matrix:
  - DEVICE_NAME: raspberry-pi
  - DEVICE_NAME: raspberry-pi2
  - DEVICE_NAME: raspberrypi3

script:
- make build

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin;
    make publish;
  fi
